sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t gsrao0201/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true gsrao0201/docker-react npm run test
